model_name: 'ensemble'

estimators:
  random_forest:
    model_params:
      n_estimators: 500
      max_depth: 30
      min_samples_leaf: 5
      min_samples_split: 10
      max_features: sqrt
  xgboost:
    model_params:
      n_estimators: 3000
      learning_rate: 0.025
      max_depth: 35
    early_stopping:
      enabled: True
      stopping_rounds: 50
  lightgbm:
    model_params:
      n_estimators: 5000
      learning_rate: 0.001
      num_leaves: 500
      max_depth: 200
      min_child_samples: 20
    early_stopping:
      enabled: True
      stopping_rounds: 75

model_output_paths:
  dir: 'models'
  model: 'models/ensemble.joblib'
  scaler: 'models/ensemble_scaler.joblib'

preprocessing:
  test_size: 0.2
  eval_size: 0.15
  amount_col: 'Amount'

voting: 'soft'