model_name: 'lightgbm'

model_output_paths:
  dir: 'models'
  model: 'models/lightgbm.joblib'
  scaler: 'models/lightgbm_scaler.joblib'

preprocessing:
  test_size: 0.2
  eval_size: 0.15
  amount_col: 'Amount'

model_params:
  n_estimators: 5000
  learning_rate: 0.001
  num_leaves: 500
  max_depth: 200
  min_child_samples: 20

early_stopping:
  enabled: True
  stopping_rounds: 75